version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=ananthu
      - POSTGRES_PASSWORD=1717reshmi
  web:
    build:
      # path to docker file
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - db