# Generated by Django 3.1.5 on 2021-06-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0002_remove_enduser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
