# Generated by Django 3.1.5 on 2021-06-13 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0003_enduser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='enduser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='enduser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enduser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
