# Generated by Django 3.1.5 on 2021-08-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0005_auto_20210829_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='displaydeals',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
